# Generated by Django 5.2.5 on 2025-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='document_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
