# Generated by Django 5.2.5 on 2025-09-02 20:17

from django.db import migrations, models 

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description_product_is_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_number',
            # 💡 CAMBIO CLAVE: Quitamos el 'default' que usaba la función.
            # Al permitir null=True en el modelo, Django puede crear el campo sin un valor por defecto.
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('paypal', 'PayPal'), ('cash', 'Efectivo')], default='cash'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            # 💡 CAMBIO CLAVE: Quitamos el 'default' que usaba la función.
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            # ⚠️ Revisa que este path sea el correcto ahora (estaba 'products/').
            field=models.ImageField(blank=True, upload_to='templates/imgs'),
        ),
    ]