# Generated by Django 5.2.5 on 2025-09-02 20:17

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_description_product_is_offered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='document_number',
            field=models.CharField(default=store.models.Order.get_default_document_number),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Tarjeta de Crédito'), ('paypal', 'PayPal'), ('cash', 'Efectivo')], default='cash'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=store.models.Order.get_default_address, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='templates/imgs'),
        ),
    ]
