# Generated by Django 5.2.5 on 2025-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Procesadores', 'Procesadores'), ('Monitores', 'Monitores'), ('Memorias RAM', 'Memorias RAM'), ('Memorias de Almacenamiento', 'Memorias de Almacenamiento'), ('Placas de video', 'Placas de video'), ('Fuentes de energia', 'Fuentes de energia'), ('Motherboards', 'Motherboards'), ('Refrigeracion', 'Refrigeracion'), ('Gabinetes', 'Gabinetes')], default='Procesadores'),
        ),
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('canceled', 'Cancelado')], default='pending'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
