# Generated by Django 5.2.5 on 2025-09-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_recipient_name_order_shipping_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recipient_name',
            new_name='full_name',
        ),
    ]
